Assets = {
    Asset("ATLAS", "images/chocolate.xml"),
    Asset("IMAGE", "images/chocolate.tex"),
    --Asset("ATLAS", "images/peanut.xml"),
    --Asset("IMAGE", "images/peanut.tex"),
    --Asset("ATLAS", "images/toast.xml"),
    --Asset("IMAGE", "images/toast.tex"),

    Asset("ANIM", "anim/chocolate.zip"),
    --Asset("ANIM", "anim/peanut.zip"),
    --Asset("ANIM", "anim/toast.zip")
}

PrefabFiles = {
    "chocolate",
    "peanut",
    "toast"
}

local STRINGS = GLOBAL.STRINGS
local NAMES = STRINGS.NAMES
local GENERIC = STRINGS.CHARACTERS.GENERIC.DESCRIBE
local WILLOW = STRINGS.CHARACTERS.WILLOW.DESCRIBE
local WOLFGANG = STRINGS.CHARACTERS.WOLFGANG.DESCRIBE
local WENDY = STRINGS.CHARACTERS.WENDY.DESCRIBE
local WX78 = STRINGS.CHARACTERS.WX78.DESCRIBE
local WICKERBOTTOM = STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE
local WOODIE = STRINGS.CHARACTERS.WOODIE.DESCRIBE
local MAXWELL = STRINGS.CHARACTERS.WAXWELL.DESCRIBE
local WIGFRID = STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE
local WEBBER = STRINGS.CHARACTERS.WEBBER.DESCRIBE
local WINONA = STRINGS.CHARACTERS.WINONA.DESCRIBE
local WARLY = STRINGS.CHARACTERS.WARLY.DESCRIBE
local WORTOX = STRINGS.CHARACTERS.WORTOX.DESCRIBE
local WORMWOOD = STRINGS.CHARACTERS.WORMWOOD.DESCRIBE
local WURT = STRINGS.CHARACTERS.WURT.DESCRIBE
local WALTER = STRINGS.CHARACTERS.WALTER.DESCRIBE
local WANDA = STRINGS.CHARACTERS.WANDA.DESCRIBE

NAMES.CHOCOLATE = "Chocolate"
GENERIC.CHOCOLATE = "Snack."
WILLOW.CHOCOLATE = "Snack."
WOLFGANG.CHOCOLATE = "Snack."
WENDY.CHOCOLATE = "Snack."
WX78.CHOCOLATE = "Snack."
WICKERBOTTOM.CHOCOLATE = "Snack."
WOODIE.CHOCOLATE = "Snack."
MAXWELL.CHOCOLATE = "Snack."
WIGFRID.CHOCOLATE = "Snack."
WEBBER.CHOCOLATE = "Snack."
WINONA.CHOCOLATE = "Snack."
WARLY.CHOCOLATE = "Snack."
WORTOX.CHOCOLATE = "Snack."
WORMWOOD.CHOCOLATE = "Snack."
WURT.CHOCOLATE = "Snack."
WALTER.CHOCOLATE = "Snack."
WANDA.CHOCOLATE = "Snack."

NAMES.PEANUT = "Peanut"
GENERIC.PEANUT = "Snack."
WILLOW.PEANUT = "Snack."
WOLFGANG.PEANUT = "Snack."
WENDY.PEANUT = "Snack."
WX78.PEANUT = "Snack."
WICKERBOTTOM.PEANUT = "Snack."
WOODIE.PEANUT = "Snack."
MAXWELL.PEANUT = "Snack."
WIGFRID.PEANUT = "Snack."
WEBBER.PEANUT = "Snack."
WINONA.PEANUT = "Snack."
WARLY.PEANUT = "Snack."
WORTOX.PEANUT = "Snack."
WORMWOOD.PEANUT = "Snack."
WURT.PEANUT = "Snack."
WALTER.PEANUT = "Snack."
WANDA.PEANUT = "Snack."

NAMES.TOAST = "Toast"
GENERIC.TOAST = "Snack."
WILLOW.TOAST = "Snack."
WOLFGANG.TOAST = "Snack."
WENDY.TOAST = "Snack."
WX78.TOAST = "Snack."
WICKERBOTTOM.TOAST = "Snack."
WOODIE.TOAST = "Snack."
MAXWELL.TOAST = "Snack."
WIGFRID.TOAST = "Snack."
WEBBER.TOAST = "Snack."
WINONA.TOAST = "Snack."
WARLY.TOAST = "Snack."
WORTOX.TOAST = "Snack."
WORMWOOD.TOAST = "Snack."
WURT.TOAST = "Snack."
WALTER.TOAST = "Snack."
WANDA.TOAST = "Snack."

modimport("scripts/translations/russian.lua")